{
 "title": "Electricity usage",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total usage interval",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "electricity_usage",
     "query": "SELECT last(\"t1\")+last(\"t2\")-first(\"t1\")-first(\"t2\") FROM \"electricity_usage\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total usage last hour",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "electricity_usage",
     "query": "SELECT last(\"t1\")+last(\"t2\")-first(\"t1\")-first(\"t2\") FROM \"electricity_usage\" WHERE time > now() - 1h",
     "select": [
      [
       { "params": [ "t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total usage last 24h",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "electricity_usage",
     "query": "SELECT last(\"t1\")+last(\"t2\")-first(\"t1\")-first(\"t2\") FROM \"electricity_usage\" WHERE time > now() - 24h",
     "select": [
      [
       { "params": [ "t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total usage last 7d",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "electricity_usage",
     "query": "SELECT last(\"t1\")+last(\"t2\")-first(\"t1\")-first(\"t2\") FROM \"electricity_usage\" WHERE time > now() - 7d",
     "select": [
      [
       { "params": [ "t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total usage last 30d",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "electricity_usage",
     "query": "SELECT last(\"t1\")+last(\"t2\")-first(\"t1\")-first(\"t2\") FROM \"electricity_usage\" WHERE time > now() - 30d",
     "select": [
      [
       { "params": [ "t1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power failures",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity_usage",
     "select": [
      [
       { "params": [ "failures" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current electricity usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Power usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily electricity usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Night",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity_usage",
     "query": "SELECT derivative(mean(\"t1\"), 10s) FROM \"electricity_usage\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "t1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "Day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity_usage",
     "query": "SELECT derivative(mean(\"t1\"), 10s) FROM \"electricity_usage\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "t2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Power failures",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity_usage",
     "select": [
      [
       { "params": [ "failures" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}